version: '3.8'
services:
  server:
    image: serpi90/craftopia
    build:
      context: https://github.com/serpi90/craftopia-docker.git
    environment:
      UID: 1000
      GID: 1000
    ports:
      - "8787:8787/tcp"
      - "8787:8787/udp"
    restart: unless-stopped
    volumes:
      - ./game:/craftopia-server # Server files, caching this will avoid having to download the server each time
      - ./steam:/home/steam/.steam/ # Steam files, caching this will improve startup time
